import type { CapabilityGraph, Constraints, HostId } from "./types";

export const DEFAULT_CONSTRAINTS: Constraints = {
  maxGainChangeDb: 3,
  allowTrackDeletion: false,
  allowRoutingChanges: false,
  allowPluginInsertion: false,
  allowAutomationChanges: true,
  requireBackup: true,
};

const mcuSurface = {
  mixer: true,
  transport: true,
  banking: true,
  metering: true,
  parameter_feedback: true,
} as const;

export const HOSTS: CapabilityGraph[] = [
  {
    host: "logic",
    label: "Logic Pro",
    vendor: "Apple",
    protocol: "MCU",
    surface: mcuSurface,
    native: {
      track_creation: false,
      clip_editing: false,
      parameter_exact: false,
      automation: false,
      rename: false,
      take_lanes: false,
    },
    plugin_bridge: {
      audio_analysis: true,
      track_state: true,
      parameter_state: true,
      clip_ops: true,
    },
    file: { read: true, write: false },
    precision: { volume: "COARSE", pan: "COARSE", mute: "EXACT" },
    notes: "Mackie Control floor plus a thin plugin bridge. Exact fader values are not claimed.",
    agentFirst: false,
  },
  {
    host: "cubase",
    label: "Cubase",
    vendor: "Steinberg",
    protocol: "MCU",
    surface: mcuSurface,
    native: {
      track_creation: false,
      clip_editing: true,
      parameter_exact: true,
      automation: true,
      rename: true,
      take_lanes: true,
    },
    plugin_bridge: {
      audio_analysis: true,
      track_state: true,
      parameter_state: true,
      clip_ops: true,
    },
    file: { read: true, write: false },
    precision: { volume: "HIGH", pan: "HIGH", mute: "EXACT" },
    notes: "MCU for the floor; MIDI Remote unlocks semantic clip and parameter ops.",
    agentFirst: false,
  },
  {
    host: "protools",
    label: "Pro Tools",
    vendor: "Avid",
    protocol: "HUI",
    surface: { ...mcuSurface, parameter_feedback: true },
    native: {
      track_creation: false,
      clip_editing: false,
      parameter_exact: false,
      automation: false,
      rename: false,
      take_lanes: false,
    },
    plugin_bridge: {
      audio_analysis: true,
      track_state: true,
      parameter_state: false,
      clip_ops: false,
    },
    file: { read: true, write: false },
    precision: { volume: "COARSE", pan: "COARSE", mute: "EXACT" },
    notes: "HUI mixer/transport. Clip and exact parameter work stay human-assisted in this revision.",
    agentFirst: false,
  },
  {
    host: "reaper",
    label: "REAPER",
    vendor: "Cockos",
    protocol: "MCU",
    surface: mcuSurface,
    native: {
      track_creation: true,
      clip_editing: true,
      parameter_exact: true,
      automation: true,
      rename: true,
      take_lanes: true,
    },
    plugin_bridge: {
      audio_analysis: true,
      track_state: true,
      parameter_state: true,
      clip_ops: true,
    },
    file: { read: true, write: true },
    precision: { volume: "EXACT", pan: "EXACT", mute: "EXACT" },
    notes: "Deep integration reference. ReaScript makes the native layer CAP-3.",
    agentFirst: false,
  },
  {
    host: "studioone",
    label: "Studio One",
    vendor: "PreSonus",
    protocol: "MCU",
    surface: mcuSurface,
    native: {
      track_creation: false,
      clip_editing: false,
      parameter_exact: true,
      automation: true,
      rename: true,
      take_lanes: false,
    },
    plugin_bridge: {
      audio_analysis: true,
      track_state: true,
      parameter_state: true,
      clip_ops: false,
    },
    file: { read: true, write: false },
    precision: { volume: "HIGH", pan: "HIGH", mute: "EXACT" },
    notes: "Mackie Control / HUI floor with Control Link for parameter depth.",
    agentFirst: false,
  },
  {
    host: "ableton",
    label: "Ableton Live",
    vendor: "Ableton",
    protocol: "MCU",
    surface: mcuSurface,
    native: {
      track_creation: true,
      clip_editing: true,
      parameter_exact: true,
      automation: true,
      rename: true,
      take_lanes: false,
    },
    plugin_bridge: {
      audio_analysis: true,
      track_state: true,
      parameter_state: true,
      clip_ops: true,
    },
    file: { read: true, write: false },
    precision: { volume: "EXACT", pan: "HIGH", mute: "EXACT" },
    notes: "LOM / Max for Live provide semantic clip and device control.",
    agentFirst: false,
  },
  {
    host: "flstudio",
    label: "FL Studio",
    vendor: "Image-Line",
    protocol: "MCU",
    surface: { ...mcuSurface, metering: true, parameter_feedback: false },
    native: {
      track_creation: false,
      clip_editing: false,
      parameter_exact: false,
      automation: false,
      rename: false,
      take_lanes: false,
    },
    plugin_bridge: {
      audio_analysis: true,
      track_state: true,
      parameter_state: false,
      clip_ops: false,
    },
    file: { read: false, write: false },
    precision: { volume: "COARSE", pan: "COARSE", mute: "EXACT" },
    notes: "Surface compatibility only. Proprietary project files are out of scope.",
    agentFirst: false,
  },
  {
    host: "bitwig",
    label: "Bitwig Studio",
    vendor: "Bitwig",
    protocol: "MCU",
    surface: mcuSurface,
    native: {
      track_creation: true,
      clip_editing: true,
      parameter_exact: true,
      automation: true,
      rename: true,
      take_lanes: true,
    },
    plugin_bridge: {
      audio_analysis: true,
      track_state: true,
      parameter_state: true,
      clip_ops: true,
    },
    file: { read: true, write: false },
    precision: { volume: "EXACT", pan: "EXACT", mute: "EXACT" },
    notes: "Controller API is a first-class native layer.",
    agentFirst: false,
  },
  {
    host: "helix",
    label: "Helix Session",
    vendor: "Helix",
    protocol: "native",
    surface: mcuSurface,
    native: {
      track_creation: true,
      clip_editing: true,
      parameter_exact: true,
      automation: true,
      rename: true,
      take_lanes: true,
    },
    plugin_bridge: {
      audio_analysis: true,
      track_state: true,
      parameter_state: true,
      clip_ops: true,
    },
    file: { read: true, write: true },
    precision: { volume: "EXACT", pan: "EXACT", mute: "EXACT" },
    notes: "Agent-first DAW. Intent, ledger, and verification are native — no protocol translation.",
    agentFirst: true,
  },
];

export function hostById(id: HostId): CapabilityGraph {
  return HOSTS.find((h) => h.host === id) ?? HOSTS[0];
}
