// Demo session data is retained across the two archive revisions.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import type { Clip, Marker, SessionState, Track } from "./types";

const DURATION = 222;

export const CHORUS_RANGES: [number, number][] = [
  [42, 68],
  [96, 122],
  [144, 170],
  [182, 204],
];

function clip(id: string, start: number, duration: number, extra?: Partial<Clip>): Clip {
  return { id, start, duration, ...extra };
}

function full(id: string): Clip[] {
  return [clip(id, 0, DURATION)];
}

function track(partial: Omit<Track, "clips"> & { clips?: Clip[] }): Track {
  return {
    unused: false,
    missingMedia: false,
    unusedSilenceSec: 0,
    dcOffset: 0,
    clippingEvents: 0,
    takes: [],
    sends: [],
    automation: [],
    plugins: [],
    clips: partial.clips ?? full(`c_${partial.id}`),
    ...partial,
  };
}

const MARKERS: Marker[] = [
  { id: "mk_intro", name: "Intro", time: 0, duration: 12, type: "intro" },
  { id: "mk_v1", name: "Verse 1", time: 12, duration: 30, type: "verse" },
  { id: "mk_c1", name: "Chorus 1", time: 42, duration: 26, type: "chorus" },
  { id: "mk_v2", name: "Verse 2", time: 68, duration: 28, type: "verse" },
  { id: "mk_c2", name: "Chorus 2", time: 96, duration: 26, type: "chorus" },
  { id: "mk_br", name: "Bridge", time: 122, duration: 22, type: "bridge" },
  { id: "mk_c3", name: "Chorus 3", time: 144, duration: 26, type: "chorus" },
  { id: "mk_c4", name: "Chorus 4", time: 182, duration: 22, type: "chorus" },
  { id: "mk_out", name: "Outro", time: 204, duration: 18, type: "outro" },
];

export function createDemoSession(): SessionState {
  const tracks: Track[] = [
    track({
      id: "tr_kick",
      index: 1,
      name: "Kick",
      tint: 0,
      kind: "audio",
      volumeDb: -6.2,
      pan: 0,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -3.1,
      truePeakDb: -2.8,
      lufsIntegrated: -22.4,
      rmsDb: -18.6,
      plugins: ["EQ", "Comp"],
      waveformSeed: 11,
    }),
    track({
      id: "tr_snare",
      index: 2,
      name: "Snare",
      tint: 1,
      kind: "audio",
      volumeDb: -8.4,
      pan: 0.04,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -4.2,
      truePeakDb: -3.9,
      lufsIntegrated: -24.1,
      rmsDb: -20.8,
      plugins: ["EQ", "Comp", "Transient"],
      waveformSeed: 23,
    }),
    track({
      id: "tr_hats",
      index: 3,
      name: "Hats",
      tint: 2,
      kind: "audio",
      volumeDb: -12.6,
      pan: -0.12,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -8.4,
      truePeakDb: -8.1,
      lufsIntegrated: -28.7,
      rmsDb: -24.2,
      plugins: ["EQ"],
      waveformSeed: 31,
    }),
    track({
      id: "tr_ohl",
      index: 4,
      name: "OH L",
      tint: 0,
      kind: "audio",
      volumeDb: -11.2,
      pan: -0.72,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -7.6,
      truePeakDb: -7.2,
      lufsIntegrated: -26.4,
      rmsDb: -21.9,
      plugins: ["EQ"],
      waveformSeed: 41,
    }),
    track({
      id: "tr_ohr",
      index: 5,
      name: "OH R",
      tint: 0,
      kind: "audio",
      volumeDb: -11.2,
      pan: 0.72,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -7.4,
      truePeakDb: -7.0,
      lufsIntegrated: -26.2,
      rmsDb: -21.7,
      plugins: ["EQ"],
      waveformSeed: 47,
    }),
    track({
      id: "tr_room",
      index: 6,
      name: "Drum Room",
      tint: 3,
      kind: "audio",
      volumeDb: -16.8,
      pan: 0,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -11.2,
      truePeakDb: -10.8,
      lufsIntegrated: -31.4,
      rmsDb: -26.1,
      unusedSilenceSec: 2.4,
      plugins: ["EQ", "Comp"],
      waveformSeed: 59,
      clips: [
        clip("c_room_sil", 0, 2.4, { silent: true }),
        clip("c_room", 2.4, DURATION - 2.4),
      ],
    }),
    track({
      id: "tr_perc",
      index: 7,
      name: "Perc",
      tint: 1,
      kind: "audio",
      volumeDb: -18.4,
      pan: 0.22,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -14.8,
      truePeakDb: -14.5,
      lufsIntegrated: -36.2,
      rmsDb: -30.1,
      unused: true,
      plugins: [],
      waveformSeed: 67,
      clips: [clip("c_perc", 96, 26)],
    }),
    track({
      id: "tr_bass",
      index: 8,
      name: "Bass",
      tint: 4,
      kind: "audio",
      volumeDb: -7.1,
      pan: 0,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -4.6,
      truePeakDb: -4.2,
      lufsIntegrated: -20.8,
      rmsDb: -16.4,
      plugins: ["EQ", "Sat", "Comp"],
      waveformSeed: 73,
    }),
    track({
      id: "tr_gtrbus",
      index: 9,
      name: "Guitar Bus",
      tint: 1,
      kind: "bus",
      volumeDb: 1.2,
      pan: 0,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -1.1,
      truePeakDb: -0.6,
      lufsIntegrated: -14.8,
      rmsDb: -12.2,
      targetDb: -3.5,
      plugins: ["Comp", "Sat", "EQ"],
      waveformSeed: 79,
      clips: [],
    }),
    track({
      id: "tr_gtrl",
      index: 10,
      name: "Gtr L",
      tint: 1,
      kind: "audio",
      volumeDb: -9.4,
      pan: -0.58,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -5.8,
      truePeakDb: -5.4,
      lufsIntegrated: -23.1,
      rmsDb: -18.9,
      sends: [{ dest: "tr_gtrbus", db: 0 }],
      plugins: ["Amp", "IR"],
      waveformSeed: 83,
    }),
    track({
      id: "tr_gtrr",
      index: 11,
      name: "Gtr R",
      tint: 1,
      kind: "audio",
      volumeDb: -9.6,
      pan: 0.58,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -6.0,
      truePeakDb: -5.6,
      lufsIntegrated: -23.4,
      rmsDb: -19.1,
      sends: [{ dest: "tr_gtrbus", db: 0 }],
      plugins: ["Amp", "IR"],
      waveformSeed: 89,
    }),
    track({
      id: "tr_acoustic",
      index: 12,
      name: "Acoustic",
      tint: 3,
      kind: "audio",
      volumeDb: -13.2,
      pan: -0.18,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -8.9,
      truePeakDb: -8.5,
      lufsIntegrated: -27.6,
      rmsDb: -22.4,
      plugins: ["EQ", "Comp"],
      waveformSeed: 97,
    }),
    track({
      id: "tr_rhodes",
      index: 13,
      name: "Rhodes",
      tint: 5,
      kind: "audio",
      volumeDb: -14.8,
      pan: 0.14,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -9.6,
      truePeakDb: -9.2,
      lufsIntegrated: -29.1,
      rmsDb: -24.0,
      plugins: ["Chorus", "EQ"],
      waveformSeed: 101,
    }),
    track({
      id: "tr_lead",
      index: 14,
      name: "Lead Vocal",
      tint: 6,
      kind: "audio",
      volumeDb: -4.0,
      pan: 0,
      mute: false,
      solo: false,
      arm: false,
      peakDb: 0.4,
      truePeakDb: 0.8,
      lufsIntegrated: -16.4,
      rmsDb: -12.1,
      clippingEvents: 3,
      plugins: ["Comp", "De-ess", "EQ", "Delay"],
      waveformSeed: 107,
      takes: [
        {
          id: "tk_1",
          name: "Take 1",
          snrDb: 18.2,
          clippingEvents: 2,
          pitchStability: 0.71,
          timingStability: 0.68,
          noiseFloorDb: -48.4,
          selected: false,
          archived: false,
        },
        {
          id: "tk_2",
          name: "Take 2",
          snrDb: 24.1,
          clippingEvents: 0,
          pitchStability: 0.91,
          timingStability: 0.88,
          noiseFloorDb: -56.2,
          selected: true,
          archived: false,
        },
        {
          id: "tk_3",
          name: "Take 3",
          snrDb: 23.4,
          clippingEvents: 0,
          pitchStability: 0.89,
          timingStability: 0.9,
          noiseFloorDb: -55.1,
          selected: false,
          archived: false,
        },
        {
          id: "tk_4",
          name: "Take 4",
          snrDb: 22.3,
          clippingEvents: 1,
          pitchStability: 0.84,
          timingStability: 0.79,
          noiseFloorDb: -51.6,
          selected: false,
          archived: false,
        },
      ],
      automation: [
        { time: 0, db: -4.0 },
        { time: 42, db: -4.0 },
        { time: 43, db: -2.8 },
        { time: 67, db: -2.8 },
        { time: 68, db: -4.0 },
        { time: 96, db: -4.0 },
        { time: 97, db: -5.5 },
        { time: 121, db: -5.5 },
        { time: 122, db: -4.0 },
        { time: 144, db: -4.0 },
        { time: 145, db: -3.2 },
        { time: 169, db: -3.2 },
        { time: 170, db: -4.0 },
        { time: 182, db: -4.0 },
        { time: 204, db: -4.0 },
      ],
    }),
    track({
      id: "tr_harm",
      index: 15,
      name: "Harm Vocal",
      tint: 6,
      kind: "audio",
      volumeDb: -11.4,
      pan: 0.08,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -6.8,
      truePeakDb: -6.4,
      lufsIntegrated: -24.8,
      rmsDb: -19.6,
      plugins: ["Comp", "EQ"],
      waveformSeed: 109,
      clips: [clip("c_harm1", 42, 26), clip("c_harm2", 96, 26), clip("c_harm3", 144, 60)],
    }),
    track({
      id: "tr_bg",
      index: 16,
      name: "BG Vox",
      tint: 6,
      kind: "audio",
      volumeDb: -13.8,
      pan: 0,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -8.2,
      truePeakDb: -7.8,
      lufsIntegrated: -27.2,
      rmsDb: -22.0,
      plugins: ["Comp", "EQ", "Verb"],
      waveformSeed: 113,
      clips: [clip("c_bg1", 96, 26), clip("c_bg2", 144, 62)],
    }),
    track({
      id: "tr_pad",
      index: 17,
      name: "Pad",
      tint: 5,
      kind: "audio",
      volumeDb: -18.6,
      pan: 0,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -14.1,
      truePeakDb: -13.8,
      lufsIntegrated: -32.4,
      rmsDb: -26.8,
      plugins: ["Filter"],
      waveformSeed: 127,
    }),
    track({
      id: "tr_fx",
      index: 18,
      name: "FX",
      tint: 2,
      kind: "audio",
      volumeDb: -20.2,
      pan: 0.1,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -12.4,
      truePeakDb: -12.0,
      lufsIntegrated: -34.8,
      rmsDb: -28.6,
      plugins: ["Delay", "Verb"],
      waveformSeed: 131,
      clips: [clip("c_fx1", 40, 8), clip("c_fx2", 120, 10), clip("c_fx3", 180, 12)],
    }),
    track({
      id: "tr_scratch",
      index: 19,
      name: "Scratch Gtr",
      tint: 7,
      kind: "audio",
      volumeDb: -12.0,
      pan: 0,
      mute: true,
      solo: false,
      arm: false,
      peakDb: -90,
      truePeakDb: -90,
      lufsIntegrated: -70,
      rmsDb: -70,
      missingMedia: true,
      plugins: [],
      waveformSeed: 139,
      clips: [clip("c_scratch", 0, DURATION, { missing: true })],
    }),
    track({
      id: "tr_master",
      index: 20,
      name: "Master",
      tint: 7,
      kind: "master",
      volumeDb: -0.2,
      pan: 0,
      mute: false,
      solo: false,
      arm: false,
      peakDb: -0.8,
      truePeakDb: -0.31,
      lufsIntegrated: -11.7,
      rmsDb: -9.4,
      plugins: ["EQ", "Comp", "Limiter"],
      waveformSeed: 149,
      clips: [],
    }),
  ];

  return {
    name: "Night Shift",
    artist: "Demo Mix",
    tempo: 92,
    sampleRate: 48000,
    duration: DURATION,
    playhead: 0,
    playing: false,
    tracks,
    markers: MARKERS,
    targets: { guitarBusDb: -3.5, masterTruePeakDb: -1.0 },
  };
}

export function cloneSession(session: SessionState): SessionState {
  return structuredClone(session);
}

export function mixerTracks(session: SessionState): Track[] {
  return session.tracks.filter((t) => t.kind !== "master");
}

export function masterTrack(session: SessionState): Track {
  return session.tracks.find((t) => t.kind === "master") ?? session.tracks[session.tracks.length - 1];
}

export function findTrack(session: SessionState, id: string): Track | undefined {
  return session.tracks.find((t) => t.id === id);
}

export const trackById = findTrack;

export function chorusMarkers(session: SessionState): Marker[] {
  return session.markers.filter((m) => m.type === "chorus");
}
